
project_id = "lbwjesrgernvjiorktia"

[functions.send-quiz-confirmation]
verify_jwt = false

[functions.facebook-conversions-api]
verify_jwt = false

[functions.test-email]
verify_jwt = false

[functions.update-email-settings]
verify_jwt = false

[functions.enqueue-email-sequence]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = false

[functions.email-open]
verify_jwt = false

[functions.email-click]
verify_jwt = false

[functions.email-unsubscribe]
verify_jwt = false
