// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xflfbousrubboovxhmwi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhmbGZib3VzcnViYm9vdnhobXdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1MjYzNDAsImV4cCI6MjA3MjEwMjM0MH0.ZSMWl-yvNgMgFOQl4-enE0iX5lPXQ5-EQInn-zCo6p0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});