// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lbwjesrgernvjiorktia.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxid2plc3JnZXJudmppb3JrdGlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1MzYyNzMsImV4cCI6MjA3MjExMjI3M30.s9fNB-C6kq0Kd98PxzYKxiH9hFr9yW_gddVXQJoSU1c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});